# This workflow is an example of DevOps practices applied in daily testing.
# The main feature of this WorkFlow is Figlet, an ascii art on these executions.

# ===============================================
# Yo can see some of my skills on my sites:      |
# https://www.linkedin.com/in/arodriguezfarias/  |
# https://rodriguezfarias.com/                   |
# ==============================================

name: QA Engineer | Antonio Rodriguez Farias

on:
  schedule:
    - cron: '*/10 * * * *'
  # workflow_dispatch:

jobs:
  test_figlet:
    if: github.event.schedule == '*/10 * * * *'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    #defaults:
      #run:
        #working-directory: Jenkins-CI
    env:
      GH_TOKEN: ${{ secrets.PAT }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: test1

      - name: Install & Run Figlet
        id: installFiglet
        if: always()
        run: |
          sudo apt install -y figlet
          figlet -c Antonio Rodriguez > file.txt
          date >> file.txt

      - name: Date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Upload Figlet File
        id: uploadFile
        uses: actions/upload-artifact@v4
        with:
          name: report-${{ env.DATE }}
          path: file.txt

      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "QA Engineer
          Co-authored-by: AntoniHub <abgrodriguezfarias@gmail.com>"
 
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT }}
          branch: "test1"
          force: true

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          source_branch: "test1"
          github_token: ${{ secrets.PAT }}
          pr_title: "QA Engineer | Antonio Rodriguez Farias"
          pr_body: |
            :wave: Hi, I am Antonio Rodriguez Farias

            🚀 About me
            Software QA Engineer with experience in Frontend, Backend, Continuous Integration, Databases (SQL and NoSQL), UX/UI, Mobile, Architecture, Linux / macOS / Windows testing.

            📊 Master Degree in Big Data - Catholic University of Avila
            🔒 Post Graduate Diploma in Defensive Cybersecurity
            💡 Diploma in Machine Learning | AI applied to Business
            📌 Continuous Testing with GitHub Actions
            📌 API Testing with Postman & Python
            📌 Frontend Testing with Selenium WebDriver
            📌 Backend Testing with Pytest, SQL & NoSQL
            📌 Linux Testing with Vagrant & VirtualBox
            📌 Mobile Testing with Android SDK & iOS
            📝 I write in depth on my website about myself [rodriguezfarias.com](https://rodriguezfarias.com/)
          pr_label: "automerge"

      - name: automerge
        uses: "pascalgn/automerge-action@v0.16.3"
        env:
          GITHUB_TOKEN: "${{ secrets.PAT }}"
      - name: feedback
        if: ${{ steps.automerge.outputs.mergeResult == 'merged' }}
        run: |
          echo "Pull request ${{ steps.automerge.outputs.pullRequestNumber }} merged!"
